### ISSUE TITLE
Switch classes in experiment.properties

### ISSUE THREAD

**Issue by zauster** [phelps-sg/jabm#4]
Hey,
i have an agent with a certain strategy. There are two possible implementations of this strategy. I wondered if it's possible to define an `experiment.properties` file that can then switch the implementation for me, without me manually commenting and uncommenting the respective beans in the `model.xml` file.

I tried something like:
```
strategyBean.class = abm.strategies.Strategy1:abm.strategies.Strategy2
```
where the `strategyBean` in defined in the `model.xml`.

But that doesn't work; I encountered a `IllegalArgumentException`:
```
Exception in thread "main" java.lang.IllegalArgumentException: householdsConsumptionStrategy.class
	at net.sourceforge.jabm.VariableBindingsIterator.getType(VariableBindingsIterator.java:113)
	at net.sourceforge.jabm.VariableBindingsIterator.parseVarFile(VariableBindingsIterator.java:88)
	at net.sourceforge.jabm.VariableBindingsIterator.<init>(VariableBindingsIterator.java:63)
	at net.sourceforge.jabm.SimulationManager.setup(SimulationManager.java:201)
	at net.sourceforge.jabm.SimulationManager.run(SimulationManager.java:130)
	at net.sourceforge.jabm.SimulationManager.main(SimulationManager.java:219)
	at benchmark.Main.main(Main.java:24)
```
Do you know of a way to get that to work?

**Comment by phelps-sg** [comment]
You can create two different beans corresponding to the two different classes of strategy.  You can then switch strategies through the `strategy` property of an agent, e.g.:

~~~
agent.strategy = householdsConsumptionStrategyA
~~~

or

~~~
agent.strategy = householdsConsumptionStrategyB
~~~

where `agent` is a bean which implements the `Agent` strategy, and therefore has a `strategy` property.

e.g. in the El Farol Bar example in the repo, you could configure

~~~
patronAgent.strategy = movingAveragePredictionStrategy
~~~
or
~~~
patronAgent.strategy = autoRegressivePredictionStrategy
~~~

**Comment by zauster** [comment]
Thanks a lot!
